{"uid":"b1a8273437954620fa374b796ffaacdd","children":[{"name":"test_success","uid":"579646d8d6275091","parentUid":"b1a8273437954620fa374b796ffaacdd","status":"passed","time":{"start":1747896387994,"stop":1747896387994,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_failure","uid":"6e72d730c5ec79df","parentUid":"b1a8273437954620fa374b796ffaacdd","status":"failed","time":{"start":1747896387995,"stop":1747896387996,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_xfailure","uid":"4307d49deaf3b2a7","parentUid":"b1a8273437954620fa374b796ffaacdd","status":"skipped","time":{"start":1747896388010,"stop":1747896388010,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["@pytest.mark.xfail(raises=<class 'RuntimeError'>)"]}],"name":"behaviors"}